[package]
name = "engine-q"
version = "0.1.0"
edition = "2018"

[dependencies]
reedline = {git = "https://github.com/jntrnr/reedline", branch = "main"}
nu-ansi-term = "0.32.0"

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.7"
pretty_assertions = "0.7.2"
